# Generated by Django 3.2 on 2023-11-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231114_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(help_text='Идентификатор категории произведения. Не более 50 символов. Разрешены символы латиницы и символы: ^[-a-zA-Z0-9_]+$', unique=True, verbose_name='URL категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Идентификатор жанра. Не более 50 символов. Разрешены символы латиницы и символы: ^[-a-zA-Z0-9_]+$', unique=True, verbose_name='URL жанра'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.categories', verbose_name='Тип произведения'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.genre', verbose_name='Жанр(ы) произведения'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(verbose_name='Год релиза'),
        ),
    ]
